Repository acts-project/vecmem, pull requests merged in 2021-09, with the labels that each got.

#98 Memory Resource Source Detection Update, main branch (2021.09.06.)
  core/CMakeLists.txt
  core/include/vecmem/memory/memory_resource.hpp
  core/include/vecmem/memory/polymorphic_allocator.hpp
Labels: enhancement

#94 Jagged Vector Improvements, main branch (2021.08.25.)
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/utils/copy.hpp
  core/include/vecmem/utils/impl/copy.ipp
Labels: enhancement

#100 Windows Compatibility, main branch (2021.09.11.)
  cmake/vecmem-compiler-options-cpp.cmake
  cmake/vecmem-functions.cmake
  cmake/vecmem-googletest.cmake
  cmake/vecmem-options.cmake
  core/CMakeLists.txt
  cuda/CMakeLists.txt
  hip/CMakeLists.txt
  sycl/CMakeLists.txt
Labels: enhancement

#101 Resolve MSVC Warnings, main branch (2021.09.13.)
  cmake/vecmem-compiler-options-cpp.cmake
  core/include/vecmem/containers/impl/jagged_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  tests/core/test_core_array.cpp
  tests/core/test_core_containers.cpp
  tests/core/test_core_contiguous_memory_resource.cpp
  tests/core/test_core_device_containers.cpp
  tests/core/test_core_jagged_vector_view.cpp
  tests/core/test_core_memory_resources.cpp
  tests/core/test_core_static_vector.cpp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_containers_kernels.cuh
  tests/cuda/test_cuda_jagged_vector_view_kernels.cu
  tests/cuda/test_cuda_memory_resources.cpp
Labels: enhancement

#102 Windows 10 DPC++ Compatibility, main branch (2021.09.15.)
  cmake/sycl/CMakeDetermineSYCLCompiler.cmake
  cmake/sycl/CMakeSYCLCompiler.cmake.in
  cmake/sycl/CMakeSYCLInformation.cmake
  cmake/sycl/CMakeTestSYCLCompiler.cmake
  cmake/vecmem-compiler-options-cpp.cmake
  cmake/vecmem-compiler-options-sycl.cmake
  tests/sycl/test_sycl_containers.sycl
  tests/sycl/test_sycl_jagged_containers.sycl
  tests/sycl/test_sycl_memory_resources.cpp
Labels: enhancement

#103 macOS Warning Fix, main branch (2021.09.18.)
  cmake/vecmem-googletest.cmake
Labels: enhancement

#104 CMake 3.21+ Compatibility, main branch (2021.09.19.)
  cmake/sycl/CMakeSYCLInformation.cmake
Labels: enhancement

#111 Constexpr Capability For vecmem::static_array, main branch (2021.09.26.)
  core/include/vecmem/containers/impl/static_array.ipp
  core/include/vecmem/containers/static_array.hpp
  tests/core/test_core_containers.cpp
Labels: bug

#108 MSVC Fixes and CI, main branch (2021.09.24.)
  .github/workflows/builds.yml
  core/CMakeLists.txt
  core/include/vecmem/utils/debug.hpp
  tests/core/test_core_default_resource.cpp
Labels: bug, cicd

#115 Fix duplicate allocation bug in binary page allocator
  core/src/memory/binary_page_memory_resource.cpp
Labels: bug

#110 Copy Improvements, main branch (2021.09.24.)
  core/include/vecmem/utils/copy.hpp
  core/include/vecmem/utils/impl/copy.ipp
  tests/core/test_core_copy.cpp
Labels: enhancement

#112 CMake 3.21+ & HIP 4.2+ Support, main branch (2021.09.26.)
  cmake/vecmem-check-language.cmake
Labels: enhancement
