Repository acts-project/vecmem, pull requests merged in 2021-12, with the labels that each got.

#148 Add a simple suite of memory benchmarks
  .github/workflows/builds.yml
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/core/CMakeLists.txt
  benchmarks/core/benchmark_core.cpp
  benchmarks/cuda/CMakeLists.txt
  benchmarks/cuda/benchmark_cuda.cpp
  benchmarks/googlebenchmark/CMakeLists.txt
Labels: enhancement

#153 CUDA Windows Fix, main branch (2021.12.09.)
  cuda/include/vecmem/utils/cuda/stream_wrapper.hpp
Labels: bug

#152 Static Array Update, main branch (2021.12.09.)
  core/include/vecmem/containers/details/static_array_traits.hpp
  core/include/vecmem/containers/details/static_vector_traits.hpp
  core/include/vecmem/containers/impl/static_array.ipp
  core/include/vecmem/containers/static_array.hpp
  core/include/vecmem/containers/static_vector.hpp
  core/include/vecmem/utils/type_traits.hpp
  tests/core/test_core_containers.cpp
  tests/core/test_core_static_array.cpp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_containers_kernels.cuh
  tests/hip/test_hip_containers.cpp
  tests/hip/test_hip_containers_kernels.hip
  tests/hip/test_hip_containers_kernels.hpp
  tests/sycl/test_sycl_containers.sycl
Labels: bug

#149 Implement a custom main function for CUDA tests
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_main.cpp
Labels: tests

#156 Use new unique pointers internally
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/data/jagged_vector_buffer.hpp
  core/include/vecmem/containers/data/jagged_vector_data.hpp
  core/include/vecmem/containers/data/vector_buffer.hpp
  core/include/vecmem/containers/impl/array.ipp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/containers/impl/jagged_vector_data.ipp
  core/include/vecmem/containers/impl/vector_buffer.ipp
  core/include/vecmem/memory/deallocator.hpp
  core/src/memory/deallocator.cpp
Labels: refactor
