Repository acts-project/vecmem, pull requests merged in 2021-02, with the labels that each got.

#8 SYCL Code Addition, main branch (2021.02.09.)
  .github/workflows/builds.yml
  CMakeLists.txt
  cmake/vecmem-compiler-options-cpp.cmake
  cmake/vecmem-options.cmake
  sycl/CMakeLists.txt
  sycl/include/vecmem/memory/sycl/direct_memory_manager.hpp
  sycl/include/vecmem/utils/sycl/device_selector.hpp
  sycl/src/memory/sycl/direct_memory_manager.cpp
  sycl/src/utils/sycl/device_selector.cpp
  tests/CMakeLists.txt
  tests/sycl/CMakeLists.txt
  tests/sycl/test_sycl_allocators.cpp
  tests/sycl/test_sycl_containers.cpp
Labels: enhancement

#12 VSCode DevContainer Setup, main branch (2021.02.12.)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/c_cpp_properties.json
Labels: enhancement

#16 Separate CUDA container test kernel from its driver
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_containers_kernels.cuh
Labels: refactor, tests

#15 Add basic definitions for memory resource architecture
  core/CMakeLists.txt
  core/include/vecmem/containers/vector.hpp
  core/include/vecmem/memory/resources/memory_resource.hpp
Labels: refactor
