Repository acts-project/vecmem, pull requests merged in 2021-03, with the labels that each got.

#17 Migrate core CPU code to use memory resources
  core/CMakeLists.txt
  core/include/vecmem/memory/host_memory_resource.hpp
  core/src/memory/host_memory_resource.cpp
  tests/core/test_core_allocators.cpp
Labels: refactor

#19 Link against and include the CUDA runtime library for C++ code, main branch (2021.03.01.)
  core/include/vecmem/utils/types.hpp
  cuda/CMakeLists.txt
  cuda/src/memory/cuda/arena_memory_manager.cpp
  cuda/src/memory/cuda/direct_memory_manager.cpp
  cuda/src/utils/cuda_error_handling.cpp
  cuda/src/utils/cuda_error_handling.hpp
  tests/cuda/test_cuda_containers_kernels.cu
Labels: refactor

#22 Make Github Actions workflows compatible with act
  .github/workflows/builds.yml
Labels: cicd

#21 Remove the default value for the memory manager
  core/src/memory/memory_manager.cpp
Labels: refactor

#23 HIP Build Cleanup, main branch (2021.03.01.)
  cmake/hip/CMakeDetermineHIPCompiler.cmake
  cmake/hip/CMakeHIPCompiler.cmake.in
  cmake/hip/CMakeHIPInformation.cmake
  cmake/vecmem-compiler-options-cuda.cmake
  cmake/vecmem-compiler-options-hip.cmake
  core/include/vecmem/utils/types.hpp
  hip/CMakeLists.txt
  hip/src/memory/hip/direct_memory_manager.hip
  hip/src/utils/hip_error_handling.hip
  hip/src/utils/hip_error_handling.hpp
  tests/hip/test_hip_containers.hip
Labels: bug, enhancement

#24 Remove the old-style core memory manager
  core/CMakeLists.txt
  core/include/vecmem/memory/host_memory_manager.hpp
  core/src/memory/host_memory_manager.cpp
Labels: cleanup

#20 Migrate CUDA code to use memory resources
  cuda/CMakeLists.txt
  cuda/include/vecmem/memory/cuda/device_memory_resource.hpp
  cuda/include/vecmem/memory/cuda/host_memory_resource.hpp
  cuda/include/vecmem/memory/cuda/managed_memory_resource.hpp
  cuda/src/memory/cuda/device_memory_resource.cpp
  cuda/src/memory/cuda/host_memory_resource.cpp
  cuda/src/memory/cuda/managed_memory_resource.cpp
  cuda/src/utils/cuda_wrappers.cpp
  cuda/src/utils/cuda_wrappers.hpp
  tests/cuda/test_cuda_allocators.cpp
  tests/cuda/test_cuda_containers.cpp
Labels: refactor

#25 vecmem::array, main branch (2021.03.02.)
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/array.ipp
  tests/core/CMakeLists.txt
  tests/core/test_core_arrays.cpp
Labels: enhancement

#28 Remove old-style memory management in CUDA code
  cuda/CMakeLists.txt
  cuda/include/vecmem/memory/cuda/arena_memory_manager.hpp
  cuda/include/vecmem/memory/cuda/direct_memory_manager.hpp
  cuda/src/memory/cuda/arena_memory_manager.cpp
  cuda/src/memory/cuda/direct_memory_manager.cpp
  tests/cuda/test_cuda_allocators.cpp
  tests/cuda/test_cuda_containers.cpp
Labels: cleanup

#27 Add an RAII CUDA device switching mechanism
  cuda/CMakeLists.txt
  cuda/src/memory/cuda/device_memory_resource.cpp
  cuda/src/utils/select_device.cpp
  cuda/src/utils/select_device.hpp
Labels: enhancement, refactor

#26 Implement a binary paging memory manager
  core/CMakeLists.txt
  core/include/vecmem/memory/binary_page_memory_resource.hpp
  core/src/memory/binary_page_memory_resource.cpp
  tests/core/CMakeLists.txt
  tests/core/test_core_binary_page.cpp
Labels: enhancement

#29 Implement a contiguous downstream memory resource
  core/CMakeLists.txt
  core/include/vecmem/memory/contiguous_memory_resource.hpp
  core/src/memory/contiguous_memory_resource.cpp
  tests/core/CMakeLists.txt
  tests/core/test_core_contiguous_memory_resource.cpp
Labels: enhancement

#32 GoogleTest Introduction, main branch (2021.03.04.)
  cmake/vecmem-functions.cmake
  cmake/vecmem-googletest.cmake
  tests/CMakeLists.txt
  tests/core/CMakeLists.txt
  tests/core/test_core_allocators.cpp
  tests/core/test_core_arrays.cpp
  tests/core/test_core_binary_page.cpp
  tests/core/test_core_containers.cpp
  tests/core/test_core_contiguous_memory_resource.cpp
Labels: cicd, enhancement, tests

#30 SYCL Memory Resources, main branch (2021.03.03.)
  sycl/CMakeLists.txt
  sycl/include/vecmem/memory/sycl/details/memory_resource_base.hpp
  sycl/include/vecmem/memory/sycl/device_memory_resource.hpp
  sycl/include/vecmem/memory/sycl/direct_memory_manager.hpp
  sycl/include/vecmem/memory/sycl/host_memory_resource.hpp
  sycl/include/vecmem/memory/sycl/shared_memory_resource.hpp
  sycl/include/vecmem/utils/sycl/queue_wrapper.hpp
  sycl/src/memory/sycl/details/memory_resource_base.sycl
  sycl/src/memory/sycl/device_memory_resource.sycl
  sycl/src/memory/sycl/direct_memory_manager.sycl
  sycl/src/memory/sycl/host_memory_resource.sycl
  sycl/src/memory/sycl/shared_memory_resource.sycl
  sycl/src/utils/sycl/device_selector.hpp
  sycl/src/utils/sycl/device_selector.sycl
  sycl/src/utils/sycl/get_queue.hpp
  sycl/src/utils/sycl/get_queue.sycl
  sycl/src/utils/sycl/opaque_queue.hpp
  sycl/src/utils/sycl/queue_wrapper.sycl
  tests/sycl/test_sycl_allocators.cpp
  tests/sycl/test_sycl_containers.sycl
Labels: cleanup, refactor

#31 HIP Memory Resources, main branch (2021.03.04.)
  cmake/FindHIPToolkit.cmake
  hip/CMakeLists.txt
  hip/include/vecmem/memory/hip/device_memory_resource.hpp
  hip/include/vecmem/memory/hip/direct_memory_manager.hpp
  hip/include/vecmem/memory/hip/host_memory_resource.hpp
  hip/src/memory/hip/device_memory_resource.cpp
  hip/src/memory/hip/direct_memory_manager.hip
  hip/src/memory/hip/host_memory_resource.cpp
  hip/src/utils/get_device.cpp
  hip/src/utils/get_device.hpp
  hip/src/utils/hip_error_handling.cpp
  hip/src/utils/hip_error_handling.hpp
  hip/src/utils/run_on_device.hpp
  hip/src/utils/select_device.cpp
  hip/src/utils/select_device.hpp
  tests/hip/CMakeLists.txt
  tests/hip/test_hip_allocators.cpp
  tests/hip/test_hip_containers.cpp
  tests/hip/test_hip_containers.hip
  tests/hip/test_hip_containers_kernels.hip
  tests/hip/test_hip_containers_kernels.hpp
Labels: cleanup, refactor

#35 Deprecated Code Removal, main branch (2021.03.08.)
  core/CMakeLists.txt
  core/include/vecmem/allocators/allocator.hpp
  core/include/vecmem/containers/host_vector.hpp
  core/include/vecmem/memory/memory_manager.hpp
  core/include/vecmem/memory/memory_manager_interface.hpp
  tests/cuda/test_cuda_allocators.cpp
  tests/cuda/test_cuda_containers.cpp
Labels: cleanup

#36 Add a front-end allocator to wrap memory resources
  core/CMakeLists.txt
  core/include/vecmem/memory/allocator.hpp
  core/include/vecmem/memory/allocator.ipp
  core/src/memory/allocator.cpp
  tests/core/CMakeLists.txt
  tests/core/test_core_allocator.cpp
Labels: enhancement

#41 Memory Handling Update, main branch (2021.03.10.)
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/array.ipp
  core/include/vecmem/containers/details/vector_buffer.hpp
  core/include/vecmem/containers/details/vector_buffer.ipp
  core/include/vecmem/memory/deallocator.hpp
  core/src/memory/deallocator.cpp
  tests/core/CMakeLists.txt
  tests/core/test_core_arrays.cpp
  tests/core/test_core_vectors.cpp
Labels: enhancement, refactor

#43 Split memory resource header in two parts
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/details/vector_buffer.hpp
  core/include/vecmem/containers/vector.hpp
  core/include/vecmem/memory/allocator.hpp
  core/include/vecmem/memory/binary_page_memory_resource.hpp
  core/include/vecmem/memory/contiguous_memory_resource.hpp
  core/include/vecmem/memory/deallocator.hpp
  core/include/vecmem/memory/host_memory_resource.hpp
  core/include/vecmem/memory/memory_resource.hpp
  core/include/vecmem/memory/polymorphic_allocator.hpp
  core/src/memory/allocator.cpp
  core/src/memory/binary_page_memory_resource.cpp
  core/src/memory/contiguous_memory_resource.cpp
  core/src/memory/host_memory_resource.cpp
  cuda/include/vecmem/memory/cuda/device_memory_resource.hpp
  cuda/include/vecmem/memory/cuda/host_memory_resource.hpp
  cuda/include/vecmem/memory/cuda/managed_memory_resource.hpp
  cuda/include/vecmem/utils/cuda/copy.hpp
  cuda/src/memory/cuda/device_memory_resource.cpp
  cuda/src/memory/cuda/host_memory_resource.cpp
  cuda/src/memory/cuda/managed_memory_resource.cpp
  hip/include/vecmem/memory/hip/device_memory_resource.hpp
  hip/include/vecmem/memory/hip/host_memory_resource.hpp
  sycl/include/vecmem/memory/sycl/details/memory_resource_base.hpp
Labels: refactor

#44 Static Vector Update, main branch (2021.03.11.)
  cmake/vecmem-compiler-options-cpp.cmake
  core/CMakeLists.txt
  core/include/vecmem/containers/static_vector.hpp
  core/include/vecmem/containers/static_vector.ipp
  core/include/vecmem/utils/type_traits.hpp
  tests/core/CMakeLists.txt
  tests/core/test_core_containers.cpp
  tests/core/test_core_static_vector.cpp
Labels: enhancement

#46 Core Test Cleanup, main branch (2021.03.13.)
  tests/CMakeLists.txt
  tests/common/memory_resource_name_gen.cpp
  tests/common/memory_resource_name_gen.hpp
  tests/core/CMakeLists.txt
  tests/core/test_core_allocators.cpp
  tests/core/test_core_array.cpp
  tests/core/test_core_arrays.cpp
  tests/core/test_core_memory_resources.cpp
  tests/core/test_core_static_vector.cpp
  tests/core/test_core_vector.cpp
Labels: refactor, tests

#47 CUDA Test Cleanup, main branch (2021.03.15.)
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_allocators.cpp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_memory_resources.cpp
Labels: refactor, tests

#48 HIP Test Cleanup, main branch (2021.03.15.)
  tests/hip/CMakeLists.txt
  tests/hip/test_hip_allocators.cpp
  tests/hip/test_hip_containers.cpp
  tests/hip/test_hip_memory_resources.cpp
Labels: refactor, tests

#49 SYCL Test Cleanup, main branch (2021.03.15.)
  cmake/sycl/CMakeSYCLCompiler.cmake.in
  tests/sycl/CMakeLists.txt
  tests/sycl/test_sycl_allocators.cpp
  tests/sycl/test_sycl_containers.sycl
  tests/sycl/test_sycl_memory_resources.cpp
Labels: enhancement, refactor, tests

#50 GoogleTest Build Update, main branch (2021.03.16.)
  cmake/vecmem-functions.cmake
  cmake/vecmem-googletest.cmake
  tests/CMakeLists.txt
Labels: tests

#45 Implement jagged vector views
  core/CMakeLists.txt
  core/include/vecmem/containers/details/jagged_vector_view.hpp
  core/include/vecmem/containers/details/jagged_vector_view.ipp
  core/include/vecmem/containers/jagged_device_vector.hpp
  core/include/vecmem/containers/jagged_device_vector.ipp
  core/include/vecmem/containers/jagged_vector.hpp
  core/include/vecmem/containers/jagged_vector_data.hpp
  core/include/vecmem/containers/jagged_vector_data.ipp
  tests/core/CMakeLists.txt
  tests/core/test_core_jagged_vector_view.cpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_jagged_vector_view.cpp
  tests/cuda/test_cuda_jagged_vector_view_kernels.cu
  tests/cuda/test_cuda_jagged_vector_view_kernels.cuh
Labels: enhancement

#51 Layout Reorganization, main branch (2021.03.23.)
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/data/jagged_vector_data.hpp
  core/include/vecmem/containers/data/jagged_vector_view.hpp
  core/include/vecmem/containers/data/vector_buffer.hpp
  core/include/vecmem/containers/data/vector_view.hpp
  core/include/vecmem/containers/device_array.hpp
  core/include/vecmem/containers/device_vector.hpp
  core/include/vecmem/containers/impl/array.ipp
  core/include/vecmem/containers/impl/device_array.ipp
  core/include/vecmem/containers/impl/device_vector.ipp
  core/include/vecmem/containers/impl/jagged_device_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector_data.ipp
  core/include/vecmem/containers/impl/jagged_vector_view.ipp
  core/include/vecmem/containers/impl/static_vector.ipp
  core/include/vecmem/containers/impl/vector.ipp
  core/include/vecmem/containers/impl/vector_buffer.ipp
  core/include/vecmem/containers/impl/vector_view.ipp
  core/include/vecmem/containers/jagged_device_vector.hpp
  core/include/vecmem/containers/static_vector.hpp
  core/include/vecmem/containers/vector.hpp
  cuda/include/vecmem/utils/cuda/copy.hpp
  cuda/include/vecmem/utils/cuda/copy.ipp
  tests/core/test_core_device_containers.cpp
  tests/core/test_core_jagged_vector_view.cpp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_containers_kernels.cuh
  tests/cuda/test_cuda_jagged_vector_view.cpp
  tests/cuda/test_cuda_jagged_vector_view_kernels.cu
  tests/cuda/test_cuda_jagged_vector_view_kernels.cuh
  tests/hip/test_hip_containers_kernels.hip
  tests/hip/test_hip_containers_kernels.hpp
Labels: refactor

#53 CUDA CMake Requirement Fix, main branch (2021.03.24.)
  cuda/CMakeLists.txt
Labels: enhancement

#52 Jagged Vector Data Updates, main branch (2021.03.24.)
  core/CMakeLists.txt
  core/include/vecmem/containers/data/jagged_vector_data.hpp
  core/include/vecmem/containers/data/jagged_vector_view.hpp
  core/include/vecmem/containers/impl/jagged_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector_data.ipp
  core/include/vecmem/containers/impl/jagged_vector_view.ipp
  core/include/vecmem/containers/jagged_vector.hpp
  tests/core/test_core_device_containers.cpp
  tests/core/test_core_jagged_vector_view.cpp
  tests/cuda/test_cuda_jagged_vector_view.cpp
Labels: refactor, tests

#55 vecmem::jagged_device_vector Update, main branch (2021.03.26.)
  core/CMakeLists.txt
  core/include/vecmem/containers/array.hpp
  core/include/vecmem/containers/data/jagged_vector_view.hpp
  core/include/vecmem/containers/data/vector_view.hpp
  core/include/vecmem/containers/details/jagged_device_vector_iterator.hpp
  core/include/vecmem/containers/details/reverse_iterator.hpp
  core/include/vecmem/containers/device_array.hpp
  core/include/vecmem/containers/device_vector.hpp
  core/include/vecmem/containers/impl/device_array.ipp
  core/include/vecmem/containers/impl/device_vector.ipp
  core/include/vecmem/containers/impl/jagged_device_vector.ipp
  core/include/vecmem/containers/impl/jagged_device_vector_iterator.ipp
  core/include/vecmem/containers/impl/jagged_vector_view.ipp
  core/include/vecmem/containers/impl/reverse_iterator.ipp
  core/include/vecmem/containers/impl/vector_view.ipp
  core/include/vecmem/containers/jagged_device_vector.hpp
  core/include/vecmem/containers/static_vector.hpp
  core/include/vecmem/utils/type_traits.hpp
  tests/core/test_core_jagged_vector_view.cpp
  tests/cuda/test_cuda_jagged_vector_view.cpp
  tests/cuda/test_cuda_jagged_vector_view_kernels.cu
Labels: enhancement, refactor, tests

#56 vecmem::data::jagged_vector_buffer Introduction, main branch (2021.03.27.)
  core/CMakeLists.txt
  core/include/vecmem/containers/data/jagged_vector_buffer.hpp
  core/include/vecmem/containers/data/vector_buffer.hpp
  core/include/vecmem/containers/impl/jagged_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/containers/jagged_vector.hpp
  tests/core/test_core_device_containers.cpp
Labels: enhancement, tests

#59 VECMEM_DEBUG_MSG Update, main branch (2021.03.31.)
  core/include/vecmem/utils/debug.hpp
Labels: bug
