Repository acts-project/vecmem, pull requests merged in 2022-09, with the labels that each got.

#192 Aligned Host Memory Allocations, main branch (2022.07.14.)
  core/CMakeLists.txt
  core/include/vecmem/memory/details/is_aligned.hpp
  core/include/vecmem/memory/host_memory_resource.hpp
  core/src/memory/details/is_aligned.cpp
  core/src/memory/host_memory_resource.cpp
  tests/CMakeLists.txt
  tests/common/memory_resource_test_alignment.hpp
  tests/common/memory_resource_test_alignment.ipp
  tests/core/test_core_memory_resources.cpp
Labels: enhancement

#194 CMake 3.24 Compatibility, main branch (2022.09.14.)
  benchmarks/googlebenchmark/CMakeLists.txt
  tests/googletest/CMakeLists.txt
Labels: enhancement

#195 SYCL Memory Resource Exceptions, main branch (2022.09.14.)
  sycl/src/memory/sycl/device_memory_resource.sycl
  sycl/src/memory/sycl/host_memory_resource.sycl
  sycl/src/memory/sycl/shared_memory_resource.sycl
Labels: enhancement

#196 Allow use of system libraries by default
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  tests/CMakeLists.txt
Labels: improvement

#197 Jagged Vector View Redesign, main branch (2022.09.30.)
  core/include/vecmem/containers/data/jagged_vector_buffer.hpp
  core/include/vecmem/containers/data/jagged_vector_view.hpp
  core/include/vecmem/containers/impl/jagged_device_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector.ipp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/containers/impl/jagged_vector_data.ipp
  core/include/vecmem/containers/impl/jagged_vector_view.ipp
  core/include/vecmem/containers/jagged_device_vector.hpp
  core/include/vecmem/utils/copy.hpp
  core/include/vecmem/utils/impl/copy.ipp
  tests/core/test_core_device_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_jagged_vector_view_kernels.cu
  tests/hip/test_hip_containers_kernels.hip
  tests/sycl/test_sycl_jagged_containers.sycl
Labels: refactor
