Repository acts-project/vecmem, pull requests merged in 2022-07, with the labels that each got.

#186 Fix missing include in `unique_alloc_deleter.hpp`
  core/include/vecmem/memory/details/unique_alloc_deleter.hpp
Labels: bug

#185 Add additional benchmarks for buddy allocator
  benchmarks/core/benchmark_core.cpp
  benchmarks/cuda/CMakeLists.txt
  benchmarks/cuda/benchmark_cuda.cpp
Labels: improvement

#188 Archive CMake build log file in CI
  .github/workflows/builds.yml
Labels: cicd

#187 Accelerate buddy allocator internals
  core/CMakeLists.txt
  core/src/memory/binary_page_memory_resource_impl.cpp
  core/src/memory/binary_page_memory_resource_impl.hpp
Labels: improvement

#190 CUDA(+GCC) False Warning Fix, main branch (2022.07.13.)
  core/include/vecmem/containers/impl/aligned_multiple_placement.ipp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_containers.cu
  tests/cuda/test_cuda_jagged_vector_view.cu
Labels: improvement

#193 Fix bugs in new implementation of buddy allocator
  core/src/memory/binary_page_memory_resource_impl.cpp
  core/src/memory/binary_page_memory_resource_impl.hpp
Labels: bug
