Repository acts-project/vecmem, pull requests merged in 2022-01, with the labels that each got.

#158 SYCL Compatibility, main branch (2021.12.17.)
  cmake/sycl/CMakeDetermineSYCLCompiler.cmake
  cmake/sycl/CMakeSYCLCompiler.cmake.in
  cmake/sycl/CMakeSYCLInformation.cmake
  cmake/sycl/Platform/Linux-ComputeCpp-SYCL.cmake
  core/include/vecmem/memory/impl/atomic.ipp
  sycl/CMakeLists.txt
  sycl/cmake/memset_test.sycl
  sycl/src/utils/sycl/copy.sycl
  sycl/src/utils/sycl/device_selector.sycl
  tests/sycl/test_sycl_containers.sycl
  tests/sycl/test_sycl_jagged_containers.sycl
Labels: enhancement

#157 Reduce Allocations in Arena Memory Resource, main branch (2021.12.16.)
  core/src/memory/arena.cpp
  core/src/memory/arena.hpp
Labels: bug

#160 Buffer Alignment Fixes, main branch (2022.01.25.)
  core/include/vecmem/containers/data/jagged_vector_buffer.hpp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/containers/impl/vector_buffer.ipp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/cuda/test_cuda_containers_kernels.cuh
Labels: bug

#161 Improve alignment guarantees of (jagged) vector buffers
  core/include/vecmem/containers/data/jagged_vector_buffer.hpp
  core/include/vecmem/containers/details/aligned_multiple_placement.hpp
  core/include/vecmem/containers/impl/aligned_multiple_placement.ipp
  core/include/vecmem/containers/impl/jagged_vector_buffer.ipp
  core/include/vecmem/containers/impl/vector_buffer.ipp
Labels: refactor

#162 SYCL Improvements, main branch (2022.01.28.)
  cmake/vecmem-check-sycl-code-compiles.cmake
  cmake/vecmem-compiler-options-sycl.cmake
  sycl/CMakeLists.txt
  sycl/cmake/warning_test.sycl
  tests/sycl/CMakeLists.txt
Labels: bug, enhancement
