Repository acts-project/vecmem, pull requests merged in 2024-06, with the labels that each got.

#276 Add concept for atomic references
  core/include/vecmem/concepts/atomic_ref.hpp
  core/include/vecmem/memory/device_atomic_ref.hpp
  core/include/vecmem/memory/impl/device_atomic_ref.ipp
  core/include/vecmem/memory/memory_order.hpp
Labels: enhancement, refactor

#279 Windows CI Fix, main branch (2024.06.11.)
  core/CMakeLists.txt
Labels: bug, cicd

#274 Add ability to reserve bulk space in device vector
  core/include/vecmem/containers/device_vector.hpp
  core/include/vecmem/containers/impl/device_vector.ipp
  core/include/vecmem/utils/type_traits.hpp
  tests/core/test_core_device_containers.cpp
  tests/cuda/test_cuda_containers.cpp
  tests/cuda/test_cuda_containers_kernels.cu
  tests/hip/test_hip_containers.cpp
  tests/hip/test_hip_containers_kernels.hip
  tests/hip/test_hip_containers_kernels.hpp
  tests/sycl/test_sycl_containers.sycl
Labels: enhancement

#278 Add support for C++20 and C++23 CI jobs
  .github/ci_setup.sh
  .github/workflows/builds.yml
  .github/workflows/checks.yml
  cmake/hip/CMakeDetermineHIPCompiler.cmake
  cmake/hip/Platform/Linux-AMD-HIP.cmake
  cmake/sycl/CMakeDetermineSYCLCompiler.cmake
  cmake/sycl/Platform/Linux-ComputeCpp-SYCL.cmake
  cmake/sycl/Platform/Linux-IntelLLVM-SYCL.cmake
  cmake/sycl/Platform/Linux-hipSYCL-SYCL.cmake
  cmake/sycl/Platform/Windows-IntelLLVM-SYCL.cmake
  tests/cuda/CMakeLists.txt
Labels: enhancement, cicd

#275 Increase the robustness of `device_atomic_ref`
  core/include/vecmem/memory/impl/device_atomic_ref.ipp
  tests/core/CMakeLists.txt
  tests/core/test_core_atomic_ref.cpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_cuda_atomic_ref.cu
Labels: bug

#280 Introduce doxygen-awesome-css, main branch (2024.06.08.)
  .github/workflows/pages.yml
  CMakeLists.txt
  cmake/doxygen-awesome-css/CMakeLists.txt
  cmake/doxygen-awesome-css/README.md
  cmake/vecmem-options.cmake
Labels: documentation, cicd

#282 Symbol Visibility Update, main branch (2024.06.13.)
  core/CMakeLists.txt
  cuda/CMakeLists.txt
  hip/CMakeLists.txt
  sycl/CMakeLists.txt
  sycl/cmake/empty.sycl
  tests/core/CMakeLists.txt
  tests/core/test_core_ubsan.cpp
  tests/cuda/CMakeLists.txt
  tests/hip/CMakeLists.txt
  tests/sycl/CMakeLists.txt
Labels: tests, improvement
