Repository acts-project/vecmem, pull requests merged in 2024-08, with the labels that each got.

#287 Fix checkout support in CI for Ubuntu 18.04
  .github/workflows/builds.yml
Labels: bug, cicd

#281 Revert "Windows CI Fix, main branch (2024.06.11.)"
  core/CMakeLists.txt
Labels: cicd

#284 Deduplicate `empty.sycl` file
  tests/sycl/CMakeLists.txt
  tests/sycl/cmake/empty_ubsan.sycl
Labels: bug

#293 SoA GCC 11 Fix, main branch (2024.08.13.)
  core/include/vecmem/edm/details/buffer_traits.hpp
Labels: bug

#292 External Updates, main branch (2024.08.09.)
  benchmarks/googlebenchmark/CMakeLists.txt
  tests/googletest/CMakeLists.txt
Labels: improvement
